<?php
$exam_list = [
    "ssc_ban1_t001" => [
        "id" => "ssc_ban1_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_ban1_t002" => [
        "id" => "ssc_ban1_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_ban1_t003" => [
        "id" => "ssc_ban1_t003",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ৩",
    ],
    "ssc_ban2_t001" => [
        "id" => "ssc_ban2_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_ban2_t002" => [
        "id" => "ssc_ban1_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_phy_t001" => [
        "id" => "ssc_phy_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_phy_t002" => [
        "id" => "ssc_phy_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_che_t001" => [
        "id" => "ssc_che_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_che_t002" => [
        "id" => "ssc_che_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_che_t003" => [
        "id" => "ssc_che_t003",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ৩",
    ],
    "ssc_che_t004" => [
        "id" => "ssc_che_t004",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ৪",
    ],
    "ssc_acc_t001" => [
        "id" => "ssc_acc_t001",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাব বিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_acc_t002" => [
        "id" => "ssc_acc_t002",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাব বিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_acc_t003" => [
        "id" => "ssc_acc_t003",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাব বিজ্ঞান",
        "test" => "মডেল টেস্ট ৩",
    ],
    "ssc_acc_t004" => [
        "id" => "ssc_acc_t004",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাব বিজ্ঞান",
        "test" => "মডেল টেস্ট ৪",
    ],
    "ssc_bah_t001" => [
        "id" => "ssc_bah_t001",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ১",
    ],
    "ssc_bah_t002" => [
        "id" => "ssc_bah_t002",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ২",
    ],
    "ssc_bah_t003" => [
        "id" => "ssc_bah_t003",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ৩",
    ],
    "ssc_bah_t004" => [
        "id" => "ssc_bah_t004",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ৪",
    ],
];
