<?php

$monthsObj = [
    "01" => "জানুয়ারি",
    "02" => "ফেব্রুয়ারি",
    "03" => "মার্চ",
    "04" => "এপ্রিল",
    "05" => "মে",
    "06" => "জুন",
    "07" => "জুলাই",
    "08" => "আগস্ট",
    "09" => "সেপ্টেম্বর",
    "10" => "অক্টোবর",
    "11" => "নভেম্বর",
    "12" => "ডিসেম্বর",
];

$model_test_list = [
    "ssc_ban1_t001" => [
        "id" => "ssc_ban1_t001",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_ban1_t002" => [
        "id" => "ssc_ban1_t002",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_ban1_t003" => [
        "id" => "ssc_ban1_t003",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_ban1_t004" => [
        "id" => "ssc_ban1_t004",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ১ম পত্র",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],

    "ssc_agr_t001" => [
        "id" => "ssc_agr_t001",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "কৃষি শিক্ষা",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_agr_t002" => [
        "id" => "ssc_agr_t002",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "কৃষি শিক্ষা",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_agr_t003" => [
        "id" => "ssc_agr_t003",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "কৃষি শিক্ষা",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_agr_t004" => [
        "id" => "ssc_agr_t004",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "কৃষি শিক্ষা",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],

    "ssc_phy_t001" => [
        "id" => "ssc_phy_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_phy_t002" => [
        "id" => "ssc_phy_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_phy_t003" => [
        "id" => "ssc_phy_t003",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_phy_t004" => [
        "id" => "ssc_phy_t004",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "পদার্থবিজ্ঞান",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],
    "ssc_bio_t001" => [
        "id" => "ssc_bio_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "জীববিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_bio_t002" => [
        "id" => "ssc_bio_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "জীববিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_bio_t003" => [
        "id" => "ssc_bio_t003",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "জীববিজ্ঞান",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_bio_t004" => [
        "id" => "ssc_bio_t004",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "জীববিজ্ঞান",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],
    "ssc_acc_t001" => [
        "id" => "ssc_acc_t001",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাববিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_acc_t002" => [
        "id" => "ssc_acc_t002",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাববিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_acc_t003" => [
        "id" => "ssc_acc_t003",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাববিজ্ঞান",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_acc_t004" => [
        "id" => "ssc_acc_t004",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "হিসাববিজ্ঞান",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],
    "ssc_fin_t001" => [
        "id" => "ssc_fin_t001",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ফিন্যান্স ও ব্যাংকিং",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_fin_t002" => [
        "id" => "ssc_fin_t002",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ফিন্যান্স ও ব্যাংকিং",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_fin_t003" => [
        "id" => "ssc_fin_t003",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ফিন্যান্স ও ব্যাংকিং",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_fin_t004" => [
        "id" => "ssc_fin_t004",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ফিন্যান্স ও ব্যাংকিং",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],
    "ssc_bah_t001" => [
        "id" => "ssc_bah_t001",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-09",
    ],
    "ssc_bah_t002" => [
        "id" => "ssc_bah_t002",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-11",
    ],
    "ssc_bah_t003" => [
        "id" => "ssc_bah_t003",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-13",
    ],
    "ssc_bah_t004" => [
        "id" => "ssc_bah_t004",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "বাংলাদেশের ইতিহাস ও বিশ্ব সভ্যতা",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-15",
    ],
    "ssc_ban2_t001" => [
        "id" => "ssc_ban2_t001",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_ban2_t002" => [
        "id" => "ssc_ban2_t002",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_ban2_t003" => [
        "id" => "ssc_ban2_t003",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_ban2_t004" => [
        "id" => "ssc_ban2_t004",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "বাংলা ২য় পত্র",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],
    "ssc_gah_t001" => [
        "id" => "ssc_gah_t001",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "গার্হস্থ্য বিজ্ঞান",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_gah_t002" => [
        "id" => "ssc_gah_t002",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "গার্হস্থ্য বিজ্ঞান",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_gah_t003" => [
        "id" => "ssc_gah_t003",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "গার্হস্থ্য বিজ্ঞান",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_gah_t004" => [
        "id" => "ssc_gah_t004",
        "grade" => "ssc",
        "group" => "all",
        "subject" => "গার্হস্থ্য বিজ্ঞান",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],

    "ssc_che_t001" => [
        "id" => "ssc_che_t001",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_che_t002" => [
        "id" => "ssc_che_t002",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_che_t003" => [
        "id" => "ssc_che_t003",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_che_t004" => [
        "id" => "ssc_che_t004",
        "grade" => "ssc",
        "group" => "science",
        "subject" => "রসায়ন",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],
    "ssc_bau_t001" => [
        "id" => "ssc_bau_t001",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ব্যবসায় উদ্যোগ",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_bau_t002" => [
        "id" => "ssc_bau_t002",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ব্যবসায় উদ্যোগ",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_bau_t003" => [
        "id" => "ssc_bau_t003",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ব্যবসায় উদ্যোগ",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_bau_t004" => [
        "id" => "ssc_bau_t004",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "ব্যবসায় উদ্যোগ",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],
    "ssc_eco_t001" => [
        "id" => "ssc_eco_t001",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "অর্থনীতি",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_eco_t002" => [
        "id" => "ssc_eco_t002",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "অর্থনীতি",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_eco_t003" => [
        "id" => "ssc_eco_t003",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "অর্থনীতি",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_eco_t004" => [
        "id" => "ssc_eco_t004",
        "grade" => "ssc",
        "group" => "commerce",
        "subject" => "অর্থনীতি",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],
    "ssc_geo_t001" => [
        "id" => "ssc_geo_t001",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "ভূগোল ও পরিবেশ",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_geo_t002" => [
        "id" => "ssc_geo_t002",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "ভূগোল ও পরিবেশ",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_geo_t003" => [
        "id" => "ssc_geo_t003",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "ভূগোল ও পরিবেশ",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_geo_t004" => [
        "id" => "ssc_geo_t004",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "ভূগোল ও পরিবেশ",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],
    "ssc_pou_t001" => [
        "id" => "ssc_pou_t001",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "পৌরনীতি ও নাগরিকতা",
        "test" => "মডেল টেস্ট ১",
        "date" => "2022-06-10",
    ],
    "ssc_pou_t002" => [
        "id" => "ssc_pou_t002",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "পৌরনীতি ও নাগরিকতা",
        "test" => "মডেল টেস্ট ২",
        "date" => "2022-06-12",
    ],
    "ssc_pou_t003" => [
        "id" => "ssc_pou_t003",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "পৌরনীতি ও নাগরিকতা",
        "test" => "মডেল টেস্ট ৩",
        "date" => "2022-06-14",
    ],
    "ssc_pou_t004" => [
        "id" => "ssc_pou_t004",
        "grade" => "ssc",
        "group" => "arts",
        "subject" => "পৌরনীতি ও নাগরিকতা",
        "test" => "মডেল টেস্ট ৪",
        "date" => "2022-06-16",
    ],

];
